services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_COMPANY_NAME=${NEXT_PUBLIC_COMPANY_NAME}
        - NEXT_PUBLIC_HEADER_LOGIN_URL=${NEXT_PUBLIC_HEADER_LOGIN_URL}
        - NEXT_PUBLIC_DOCS_URL=${NEXT_PUBLIC_DOCS_URL}
        - NEXT_PUBLIC_CLIENTS_COUNT=${NEXT_PUBLIC_CLIENTS_COUNT}
        - NEXT_PUBLIC_NETWORK_SPEED=${NEXT_PUBLIC_NETWORK_SPEED}
        - NEXT_PUBLIC_CONSULTATION_EMAILS=${NEXT_PUBLIC_CONSULTATION_EMAILS}
        - NEXT_PUBLIC_CONSULTATION_PHONES=${NEXT_PUBLIC_CONSULTATION_PHONES}
        - NEXT_PUBLIC_SUPPORT_EMAILS=${NEXT_PUBLIC_SUPPORT_EMAILS}
        - NEXT_PUBLIC_SUPPORT_PHONES=${NEXT_PUBLIC_SUPPORT_PHONES}
        - NEXT_PUBLIC_SOCIAL_LINKS=${NEXT_PUBLIC_SOCIAL_LINKS}
    ports:
      - "3009:3000"
    environment:
      - FORMSPREE_FORM_ID=${FORMSPREE_FORM_ID}
    restart: unless-stopped
